### ISSUE TITLE
What dose the "train.txt" look like?

### ISSUE THREAD

**Issue by samylee** [davideverona/deep-crowd-counting_crowdnet#1]
Hi @davideverona ,
Thanks for sharing your method.
But i don't know how to make the file of "train.txt", could you please tell me?
It is the best for me if you can provide the "train.txt" and train-datasets.
My email address is ahuljx@126.com.
Thank you very much!

samylee

**Comment by davideverona** [comment]
Hi @samylee,
Thanks for writing.
"train.txt" altogether with "test.txt" and all hdf5 files are produced by dcc_crowdnet.ipynb python jupyter notebook, that you can find in the repository, as the result of data augmentation and ground truth density map generation process.
These files are uncompressed data ~18GB for the UCF_CC_50 dataset.
I suggest you to run the notebook to reproduce the train and val datasets, let me know if you encounter any problem.

Davide

**Comment by samylee** [comment]
Hi @davideverona ,
Thanks for your suggestions, I will try it. By the way, how fast is the method using cpu i7?
I'm looking forward to your reply, Thank you!

Samylee

**Comment by davideverona** [comment]
Hi @samylee,
I trained for 5 hours on a gpu with 7 tflops, on a cpu you will more than 10 times slower.

Davide

**Comment by samylee** [comment]
Hi @davideverona ,
I realized that the last layer of the output is 28x28, the value of the feature points are less than 1, and even negative numbers. So how do I get the final density map of the image via image mosaic? 
It is the best for me if you can provide the code (python or c++). My email address is ahuljx@126.com.
I'm looking forward to your reply. Thank you very much!

Samylee

**Comment by samylee** [comment]
Hi @davideverona ,
Could you help me? Please^_^
I realized that the last layer of the output is 28x28, the value of the feature points are less than 1, and even negative numbers. So how do I get the final density map of the image via image mosaic?
It is the best for me if you can provide the code (python or c++). My email address is ahuljx@126.com.
I'm looking forward to your reply. Thank you very much!

Samylee

**Comment by samylee** [comment]
Hi @davideverona ,
Sorry to bother you again!
The caffemodel that I trained still has some problems, so could you please provide the caffemodel for me? Thanks! And the caffemodel that you trained could be applied to low density populations?
I'm looking forward to your reply. Thank you very much!

Samylee
